language: node_js
node_js:
  - "stable"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install gnupg
  - npm i -g istanbul
  - npm i -g jasmine
after_success:
  - npm run coveralls
sudo: required

