language: node_js
node_js:
  - "stable"
  - "6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install gnupg
  - npm i -g istanbul
  - npm i -g jasmine
  - npm i -g https://github.com/btoll/dump_describes.git
after_success:
  - npm run coveralls
sudo: required

